<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.13" />
    <PackageReference Include="SharpCompress" Version="0.50.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotCruz.Notifications.Application\DotCruz.Notifications.Application.csproj" />
    <ProjectReference Include="..\DotCruz.Notifications.Contracts\DotCruz.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\DotCruz.Notifications.CrossCutting\DotCruz.Notifications.CrossCutting.csproj" />
    <ProjectReference Include="..\DotCruz.Notifications.Infrastructure\DotCruz.Notifications.Infrastructure.csproj" />
  </ItemGroup>

</Project>
